### ISSUE TITLE
Can't fetch data from user profile such as image title bio and skills

### ISSUE THREAD

**Issue by hellopratiksingh** [bobby-didcoding/resume_app#1]

**Comment by bobby-didcoding** [comment]
Are you trying to access the userprofile in the templates?
If so, you access via the request context processor;
{{request.user.userprofile.bio}}
Or 
{{me.userprofile.bio}}
Is this what you mean? 
Thanks,
Bobby

**Comment by hellopratiksingh** [comment]
I am trying to access it via {{me.userprofile.avatar.url}}
![Screenshot (154)](https://user-images.githubusercontent.com/61048532/139390679-cab84079-0ffd-4940-8837-62e05c0daf04.png)
![Screenshot (152)](https://user-images.githubusercontent.com/61048532/139390701-405e0ad7-eb95-42a2-8ead-1a4931992c88.png)
}

**Comment by bobby-didcoding** [comment]
Hiya. Have you created a superuser?

From your terminal, use this command:
python manage.py createsuperuser

Then, log in to localhost:8000/admin and add your details.

Thanks
Bobby

**Comment by hellopratiksingh** [comment]
I did but still not working
![Screenshot (155)](https://user-images.githubusercontent.com/61048532/139392504-d2e36b5d-c59e-4a48-8e47-a24a45a53642.png)

**Comment by bobby-didcoding** [comment]
Okay. I'll see if I can replicate the issue when I'm in the office & push a bug fix.
Out of interest, did you watch the tutorial on FreeCodeCamp?

**Comment by hellopratiksingh** [comment]
Yeah, thanks for creating this amazing tutorial.

**Comment by hellopratiksingh** [comment]
UPDATE*
Fixed the issue by dropping the whole db and by migrating again. now only 2 issues left which are the title is not displaying after name and 2nd one is skill bar not showing.
I will post updates

**Comment by hellopratiksingh** [comment]
UPDATE #2
All issues fixed thanks

**Comment by bobby-didcoding** [comment]
Okay, great. Thanks for keeping me posted. 
What was the issue?

**Comment by hellopratiksingh** [comment]
At first it was db issue which i fixed by dropping tables and migrating again.
And last one was a incorrect if condition in index.html file due to which it was not showing score bar.
Out of interest, can we connect on LinkedIn?

**Comment by bobby-didcoding** [comment]
Feel free to create a pull request with the fix & I will merge the code.

Yes, sure: https://www.linkedin.com/in/bobby-stearman-6a6ba749
