### ISSUE TITLE
Error in index.html file

### ISSUE THREAD

**Issue by shahbazaldiablo** [bobby-didcoding/resume_app#8]
![error at line 96](https://user-images.githubusercontent.com/70898307/142290294-e2640943-d7b6-4cb5-afda-2804527e5377.jpg)

Hi, I'm getting these errors in index.html file, and I've copied the same code from the file here, no changes but I'm getting an error.

property value expected
{
	"resource": "/h:/CodeCamp/Django/Resume_Project/resume_demo/main/templates/main/index.html",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-propertyvalueexpected",
	"severity": 8,
	"message": "property value expected",
	"source": "css",
	"startLineNumber": 96,
	"startColumn": 82,
	"endLineNumber": 96,
	"endColumn": 83
}

**Comment by Pradeep-coder** [comment]
Yes, even I have the same issue. Please anybody with a solution for this

![image](https://user-images.githubusercontent.com/52486340/142441487-8c34aed5-f647-49cb-989d-1d0e5394a2e1.png)

**Comment by bobby-didcoding** [comment]
Hi,
Sorry to hear your having issues. I'll take a look as soon as I get in front of my screen.
Thanks
Bobby

**Comment by Pradeep-coder** [comment]
Thank you for your response. That's a lovely project and would expect more
django projects in the future. Keep up the good work.

**Comment by bobby-didcoding** [comment]
HI there,
The CSS in VS Code is complaining because '{{sk.score}}' is not valid CSS (its a Django template syntax) - It only becomes valid CSS once the template is executed and rendered in  a browser.
You either need a plug-in that recognises Django template syntax or turn off html validate styles in vs code setting's.
I hope this helps.
Thanks,
Bobby

**Comment by shahbazaldiablo** [comment]
Hey Bobby, 
Thanks for all the effort you put into this... and I hope that you keep publishing great content in the future...
I'll mark this complete, and I think we'll ignore those errors as the code is executing in the browser without any errors...

**Comment by Pradeep-coder** [comment]
Awesome, thanks!
